version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: leafwheels-postgres
    environment:
      POSTGRES_DB: leafwheels
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - leafwheels-net

  app:
    build: .
    container_name: leafwheels-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/leafwheels
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - leafwheels-net

volumes:
  postgres_data:

networks:
  leafwheels-net:
