name: Frontend Build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      frontend_only: ${{ steps.check.outputs.frontend_only }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check changed files
        id: check
        run: |
          files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "$files"
          only_frontend=true
          for file in $files; do
            if [[ ! "$file" =~ ^frontend/ ]]; then
              only_frontend=false
              break
            fi
          done
          echo "frontend_only=$only_frontend" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.frontend_only == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Install dependencies
        run: npm ci
        working-directory: frontend
      - name: Build frontend
        run: npm run build
        working-directory: frontend
